Fixed optional field for `GetAvailabilityResponse`
nylas/nylas-java pull request #169
Opened 2023-11-13 21:19 UTC by mrashed-dev

# Description
In the response object for getting availability, `order` is only populated for round-robin events.

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-11-14 05:04 UTC, atejada requested changes
Sorry @mrashed-dev but this fix gets me this error

```
Required value 'timeSlots' (JSON name 'time_slots') missing at $
```

I'm trying to find the root cause but I can't

2023-11-14 20:59 UTC, mrashed-dev commented
@atejada fixed!

2023-11-14 21:30 UTC, atejada requested changes
@mrashed-dev Hate to be this kind of guy, but...

```
class com.nylas.models.GetAvailabilityResponse cannot be cast to class com.nylas.models.Response (com.nylas.models.GetAvailabilityResponse and com.nylas.models.Response are in unnamed module of loader 'app')
```

😭

2023-11-14 23:29 UTC, mrashed-dev commented
@atejada not at all, sorry for the bugs. Thanks for testing, I think we should be good now but please test and let me know!

2023-11-15 03:00 UTC, atejada approved these changes
Awesome! Thanks @mrashed-dev now it works 🥳

2023-11-15 16:14 UTC, merged